/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.ngspace.v2engine;

import java.io.IOException;

import io.github.ngspace.v2engine.utils.CachedReader;
import io.github.ngspace.v2engine.utils.CompileException;
import io.github.ngspace.v2engine.v2runtime.AV2Compiler;
import io.github.ngspace.v2engine.v2runtime.V2CompilerImpl;

public class V2Engine {
	public static AV2Compiler v2compiler = new V2CompilerImpl();
	public static CachedReader reader = new CachedReader();
	
    public static void main(String[] args) throws IOException, CompileException {
    	v2compiler.buildRuntime(reader.getFile(args[0]), args[0]).execute();
    }

	public static void log(Object string) {System.out.println(string);}
	
	public static void err (Object string) {System.out.println("\033[0;31m" + string + "\033[0m");}
	public static void warn(Object string) {System.out.println("\033[0;33m" + string + "\033[0m");}
}
